# Generated by Django 4.2.16 on 2025-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0003_remove_rixauser_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='rixauser',
            name='no_tracker_saving',
            field=models.BooleanField(default=False),
        ),
    ]
