# Generated by Django 4.1.5 on 2024-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0004_invitation_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('system_message', models.TextField()),
                ('included_plugins', models.JSONField(default=list)),
                ('document_tags', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='DashboardPermissions',
        ),
    ]
