# Generated by Django 4.2.16 on 2025-02-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0006_remove_message_seen_by_rixauser_seen_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
