# Generated by Django 4.1.5 on 2024-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_selectiontag_remove_rixauser_allowed_chat_templates_and_more'),
        ('account_managment', '0006_delete_plugintemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.selectiontag'),
        ),
    ]
