# Generated by Django 4.1.5 on 2024-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0007_invitation_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RixaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('messages_per_session', models.JSONField(blank=True, default=None, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
            ],
        ),
    ]
