# Generated by Django 4.1.5 on 2024-05-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_usertag_rename_selectiontag_pluginscope_and_more'),
        ('account_managment', '0008_rixauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.usertag'),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='configuration_write',
            field=models.ManyToManyField(related_name='configuration_write', to='dashboard.chatconfiguration'),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='scope_read',
            field=models.ManyToManyField(related_name='scope_read', to='dashboard.pluginscope'),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='scope_write',
            field=models.ManyToManyField(related_name='scope_write', to='dashboard.pluginscope'),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='user_tags',
            field=models.ManyToManyField(to='dashboard.usertag'),
        ),
    ]
