# Generated by Django 4.1.5 on 2024-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0009_alter_invitation_tags_rixauser_configuration_write_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invitation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='account_managment.usertag'),
        ),
        migrations.AlterField(
            model_name='rixauser',
            name='user_tags',
            field=models.ManyToManyField(to='account_managment.usertag'),
        ),
    ]
