# Generated by Django 4.1.5 on 2024-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_chatconfiguration_document_tags_and_more'),
        ('account_managment', '0010_usertag_alter_invitation_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rixauser',
            name='configurations_read',
            field=models.ManyToManyField(blank=True, related_name='configurations_read', to='dashboard.chatconfiguration'),
        ),
        migrations.AlterField(
            model_name='rixauser',
            name='configuration_write',
            field=models.ManyToManyField(blank=True, related_name='configuration_write', to='dashboard.chatconfiguration'),
        ),
        migrations.AlterField(
            model_name='rixauser',
            name='scope_read',
            field=models.ManyToManyField(blank=True, related_name='scope_read', to='dashboard.pluginscope'),
        ),
        migrations.AlterField(
            model_name='rixauser',
            name='scope_write',
            field=models.ManyToManyField(blank=True, related_name='scope_write', to='dashboard.pluginscope'),
        ),
        migrations.AlterField(
            model_name='rixauser',
            name='user_tags',
            field=models.ManyToManyField(blank=True, to='account_managment.usertag'),
        ),
    ]
