# Generated by Django 4.1.5 on 2024-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_chatconfiguration_system_message'),
        ('account_managment', '0011_rixauser_configurations_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='rixauser',
            name='user_tags',
        ),
        migrations.AddField(
            model_name='invitation',
            name='configuration_write',
            field=models.ManyToManyField(blank=True, related_name='invitation_configuration_write', to='dashboard.chatconfiguration'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='configurations_read',
            field=models.ManyToManyField(blank=True, related_name='invitation_configurations_read', to='dashboard.chatconfiguration'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scope_read',
            field=models.ManyToManyField(blank=True, related_name='invitation_scope_read', to='dashboard.pluginscope'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='scope_write',
            field=models.ManyToManyField(blank=True, related_name='invitation_scope_write', to='dashboard.pluginscope'),
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
