# Generated by Django 4.1.5 on 2024-08-01 16:56

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('available_to_all', models.BooleanField(default=False)),
                ('system_message', models.TextField(blank=True)),
                ('first_message', models.TextField(blank=True)),
                ('use_function_calls', models.BooleanField(default=False)),
                ('included_plugins', models.JSONField(blank=True, default=dashboard.models.generate_default_plugins)),
                ('use_document_retrieval', models.BooleanField(default=False)),
                ('document_tags', models.JSONField(blank=True, default=dashboard.models.generate_default_document_tags)),
                ('included_scopes', models.ManyToManyField(blank=True, to='dashboard.pluginscope')),
            ],
        ),
    ]
