# Generated by Django 4.1.5 on 2024-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfiguration',
            name='chat_title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
