# Generated by Django 4.1.5 on 2024-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rixauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rixauser',
            name='allowed_chat_templates',
        ),
        migrations.AddField(
            model_name='chatconfiguration',
            name='available_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatconfiguration',
            name='tags',
            field=models.ManyToManyField(to='dashboard.selectiontag'),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='allowed_tags',
            field=models.ManyToManyField(to='dashboard.selectiontag'),
        ),
    ]
