# Generated by Django 4.2.16 on 2024-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='model_key',
            new_name='model_name',
        ),
    ]
