# Generated by Django 4.1.5 on 2024-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_selectiontag_remove_rixauser_allowed_chat_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rixauser',
            name='messages_per_session',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rixauser',
            name='total_time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
