# Generated by Django 4.1.5 on 2024-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rixauser_messages_per_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rixauser',
            name='messages_per_session',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
