# Generated by Django 4.2.16 on 2024-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_model_key_conversation_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfiguration',
            name='custom_user_settings',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
