# Generated by Django 4.2.16 on 2024-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_chatconfiguration_custom_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconfiguration',
            name='custom_user_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
