# Generated by Django 4.1.5 on 2024-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0008_rixauser'),
        ('dashboard', '0005_alter_rixauser_messages_per_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SelectionTag',
            new_name='PluginScope',
        ),
        migrations.RemoveField(
            model_name='chatconfiguration',
            name='tags',
        ),
        migrations.DeleteModel(
            name='RixaUser',
        ),
    ]
