# Generated by Django 4.1.5 on 2024-05-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0010_usertag_alter_invitation_tags_and_more'),
        ('dashboard', '0006_usertag_rename_selectiontag_pluginscope_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
