# Generated by Django 4.2.16 on 2025-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_conversation_chat_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfiguration',
            name='background_message',
            field=models.TextField(blank=True, help_text='Displayed if no first message is given and no message is in the chat history'),
        ),
        migrations.AddField(
            model_name='chatconfiguration',
            name='preferred_chat_backend',
            field=models.CharField(blank=True, help_text='Preferred chat backend', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatconfiguration',
            name='first_message',
            field=models.TextField(blank=True, help_text='Displayed as the first message in the chat'),
        ),
        migrations.AlterField(
            model_name='chatconfiguration',
            name='system_message',
            field=models.TextField(blank=True, help_text='Custom instructions for the chatbot'),
        ),
    ]
