# Generated by Django 4.1.5 on 2024-05-21 08:55

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconfiguration',
            name='document_tags',
            field=models.JSONField(blank=True, default=dashboard.models.generate_default_document_tags),
        ),
        migrations.AlterField(
            model_name='chatconfiguration',
            name='included_plugins',
            field=models.JSONField(blank=True, default=dashboard.models.generate_default_plugins),
        ),
    ]
