# Generated by Django 4.1.5 on 2024-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_chatconfiguration_document_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfiguration',
            name='use_document_retrieval',
            field=models.BooleanField(default=False),
        ),
    ]
