# Generated by Django 4.1.5 on 2024-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_chatconfiguration_use_document_retrieval'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfiguration',
            name='included_scopes',
            field=models.ManyToManyField(blank=True, to='dashboard.pluginscope'),
        ),
    ]
