# Generated by Django 4.1.5 on 2024-05-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_chatconfiguration_included_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconfiguration',
            name='use_function_calls',
            field=models.BooleanField(default=False),
        ),
    ]
