# Generated by Django 4.1.5 on 2024-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_chatconfiguration_use_function_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconfiguration',
            name='system_message',
            field=models.TextField(blank=True),
        ),
    ]
